apiVersion: v1
kind: Secret
metadata:
  name: cluster-stack-variables
  namespace: system
type: Opaque
data:
  git-provider: ${GIT_PROVIDER_B64:=""}
  git-org-name: ${GIT_ORG_NAME_B64:=""}
  git-repo-name: ${GIT_REPOSITORY_NAME_B64:=""}
  git-access-token: ${GIT_ACCESS_TOKEN_B64:=""}
  oci-registry: ${OCI_REGISTRY_B64:=""}
  oci-repository: ${OCI_REPOSITORY_B64:=""}
  oci-access-token: ${OCI_ACCESS_TOKEN_B64:=""}
  oci-username: ${OCI_USERNAME_B64:=""}
  oci-password: ${OCI_PASSWORD_B64:=""}
