apiVersion: v1
kind: Secret
metadata:
  name: cluster-stack-variables
  namespace: system
type: Opaque
data:
  git-provider: ${GIT_PROVIDER_B64:=""}
  git-org-name: ${GIT_ORG_NAME_B64:=""}
  git-repo-name: ${GIT_REPOSITORY_NAME_B64:=""}
  git-access-token: ${GIT_ACCESS_TOKEN_B64:=""}
