---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cluster-x-k8s-io-v1beta1-cluster
  failurePolicy: Fail
  name: validation.cluster.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterstack-x-k8s-io-v1alpha1-clusterstack
  failurePolicy: Fail
  name: validation.clusterstack.clusterstack.x-k8s.io
  rules:
  - apiGroups:
    - clusterstack.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterstacks
  sideEffects: None
