---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
    control-plane: cso-controller-manager
  name: cso-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: cluster-stack-operator
      control-plane: cso-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        cluster.x-k8s.io/provider: cluster-stack-operator
        control-plane: cso-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect=true
        - --log-level=info
        command:
        - /manager
        - -source
        - {{ .Values.source }}
        env:
        {{- if eq .Values.source "github" }}
        - name: GIT_PROVIDER
          valueFrom:
            secretKeyRef:
              key: git-provider
              name: cso-cluster-stack-variables
        - name: GIT_ORG_NAME
          valueFrom:
            secretKeyRef:
              key: git-org-name
              name: cso-cluster-stack-variables
        - name: GIT_REPOSITORY_NAME
          valueFrom:
            secretKeyRef:
              key: git-repo-name
              name: cso-cluster-stack-variables
        - name: GIT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: git-access-token
              name: cso-cluster-stack-variables
        {{- else }}
        - name: OCI_REGISTRY
          valueFrom:
            secretKeyRef:
              key: oci-registry
              name: cso-cluster-stack-variables
        - name: OCI_REPOSITORY
          valueFrom:
            secretKeyRef:
              key: oci-repository
              name: cso-cluster-stack-variables
        - name: OCI_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: oci-access-token
              name: cso-cluster-stack-variables
        - name: OCI_USERNAME
          valueFrom:
            secretKeyRef:
              key: oci-username
              name: cso-cluster-stack-variables
        - name: OCI_PASSWORD
          valueFrom:
            secretKeyRef:
              key: oci-password
              name: cso-cluster-stack-variables
        {{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        ports:
        - containerPort: 9442
          name: hook-server-svc
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 250Mi
        volumeMounts:
        - mountPath: /tmp/k8s-hook-server/serving-certs
          name: hook-server-cert
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: cso-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - name: hook-server-cert
        secret:
          defaultMode: 420
          secretName: cso-hook-server-server-cert
      - name: cert
        secret:
          defaultMode: 420
          secretName: cso-webhook-server-cert
---
apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  annotations:
    runtime.cluster.x-k8s.io/inject-ca-from-secret: {{ .Release.Namespace }}/cso-hook-server-server-cert
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  name: cso-hook-server-extensionconfig
  namespace: {{ .Release.Namespace }}
spec:
  clientConfig:
    service:
      name: cso-hook-server-svc
      namespace: {{ .Release.Namespace }}
      port: 443
  namespaceSelector: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cso-serving-cert
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  name: cso-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: cso-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-cluster-x-k8s-io-v1beta1-cluster
    failurePolicy: Fail
    name: validation.cluster.cluster.x-k8s.io
    rules:
      - apiGroups:
          - cluster.x-k8s.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1alpha1
    clientConfig:
      service:
        name: cso-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-clusterstack-x-k8s-io-v1alpha1-clusteraddon
    failurePolicy: Fail
    name: validation.clusteraddon.clusterstack.x-k8s.io
    rules:
      - apiGroups:
          - clusterstack.x-k8s.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusteraddons
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1alpha1
    clientConfig:
      service:
        name: cso-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-clusterstack-x-k8s-io-v1alpha1-clusterstack
    failurePolicy: Fail
    name: validation.clusterstack.clusterstack.x-k8s.io
    rules:
      - apiGroups:
          - clusterstack.x-k8s.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - clusterstacks
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1alpha1
    clientConfig:
      service:
        name: cso-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-clusterstack-x-k8s-io-v1alpha1-clusterstackrelease
    failurePolicy: Fail
    name: validation.clusterstackrelease.clusterstack.x-k8s.io
    rules:
      - apiGroups:
          - clusterstack.x-k8s.io
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - clusterstackreleases
    sideEffects: None
