apiVersion: runtime.cluster.x-k8s.io/v1beta2
kind: ExtensionConfig
metadata:
  name: {{ include "cso.fullname" . }}-hook-server-extensionconfig
  annotations:
    runtime.cluster.x-k8s.io/inject-ca-from-secret: {{ .Release.Namespace }}/{{ include "cso.fullname" . }}-hook-server-server-cert
spec:
  clientConfig:
    service:
      name: {{ include "cso.fullname" . }}-hook-server-svc
      namespace: '{{ .Release.Namespace }}'
      port: 443
  namespaceSelector: {}
