---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  name: cso-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  name: cso-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  - cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  - infrastructure.clusterstack.x-k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusteraddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusteraddons/finalizers
  - clusterstackreleases/finalizers
  verbs:
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusteraddons/status
  - clusterstackreleases/status
  - clusterstacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstackreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstacks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstacks/finalizers
  verbs:
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  name: cso-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cso-leader-election-role
subjects:
- kind: ServiceAccount
  name: cso-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  name: cso-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cso-manager-role
subjects:
- kind: ServiceAccount
  name: cso-controller-manager
  namespace: {{ .Release.Namespace }}
