apiVersion: v1
kind: Service
metadata:
  name: {{ include "cso.fullname" . }}-webhook-service
  labels:
    cluster.x-k8s.io/provider: cluster-stack-operator
  {{- include "cso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    cluster.x-k8s.io/provider: cluster-stack-operator
    control-plane: cso-controller-manager
  {{- include "cso.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 }}