apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  annotations:
    runtime.cluster.x-k8s.io/inject-ca-from-secret: $(HOOK_SERVER_CERTIFICATE_NAMESPACE)/$(HOOK_SERVER_CERTIFICATE_NAME)
  name: hook-server-extensionconfig
spec:
  clientConfig:
    service:
      name: hook-server-svc
      namespace: system # Note: this assumes the test extension get deployed in the default namespace defined in its own runtime-extensions-components.yaml
      port: 443
  namespaceSelector: {}