---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  - cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusteraddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusteraddons/finalizers
  verbs:
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusteraddons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstackreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstackreleases/finalizers
  verbs:
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstackreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstacks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstacks/finalizers
  verbs:
  - delete
  - update
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - clusterstacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.clusterstack.x-k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
