name: "Setup Go"
description: "Setup Go"
runs:
  using: "composite"
  steps:
    - name: Install go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: "1.25"
        go-version-file: "go.mod"
        cache: true
        cache-dependency-path: go.sum
    - id: go-cache-paths
      shell: bash
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"
    - name: Go Mod Cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    - name: Go Build Cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
