name: Verify Pull Request
on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
# yamllint disable rule:line-length
jobs:
  pr-verify:
    runs-on: ubuntu-latest
    name: Verify Pull Request
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    steps:
      - name: Verifier action
        id: verifier
        uses: kubernetes-sigs/kubebuilder-release-tools@012269a88fa4c034a0acf1ba84c26b195c0dbab4 # v0.4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify Shellcheck
        run: make verify-shellcheck

      - name: Generate Token
        uses: actions/create-github-app-token@e8e39f73bb84fdf315a015fa3104f314c0a258b4 # v1
        id: generate-token
        with:
          app-id: ${{ secrets.SCS_APP_ID }}
          private-key: ${{ secrets.SCS_APP_PRIVATE_KEY }}

      - name: Generate Labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: .github/labeler.yaml
          repo-token: ${{ steps.generate-token.outputs.token }}

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2
        with:
          config-file: .github/labels.yaml
          token: ${{ steps.generate-token.outputs.token }}
