name: Verify Pull Request
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
# yamllint disable rule:line-length
jobs:
  pr-verify:
    runs-on: ubuntu-latest
    name: Verify Pull Request
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    steps:
      - name: Verifier action
        id: verifier
        uses: kubernetes-sigs/kubebuilder-release-tools@012269a88fa4c034a0acf1ba84c26b195c0dbab4 # v0.4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify Shellcheck
        run: make verify-shellcheck
