name: CSO Image Cache Cleaner
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Run the GC on the first day in the month at 6am
    - cron: "0 6 1 * *"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true
jobs:
  cache-cleaner:
    runs-on: ubuntu-20.04
    steps:
      # Load Golang cache build from GitHub
      - name: Load cso Golang cache build from GitHub
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        id: cache
        with:
          path: /tmp/.cache/cso
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-cso-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-cso-
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-
      - name: Create cso cache directory
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/cso
      # Clean docker's golang's cache
      - name: Clean cso Golang cache from GitHub
        shell: bash
        run: |
          rm -f /tmp/.cache/cso/go-build-cache.tar.gz
          rm -f /tmp/.cache/cso/go-pkg-cache.tar.gz
