name: Schedule - Update Bot
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 11 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json5"
env:
  LOG_LEVEL: info
  DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate.json5
# yamllint disable rule:line-length
jobs:
  update-bot:
    if: github.repository == 'SovereignCloudStack/cluster-stack-operator'
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2

        id: generate-token
        with:
          app-id: ${{ secrets.SCS_APP_ID }}
          private-key: ${{ secrets.SCS_APP_PRIVATE_KEY }}

      - name: Override default config from dispatch variables
        run: |
          echo "DRY_RUN=${{ github.event.inputs.dryRun || env.DRY_RUN }}" >> "$GITHUB_ENV"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "$GITHUB_ENV"

      - name: Renovate
        uses: renovatebot/github-action@13da59cf7cfbd3bfea72ce26752ed22edf747ce9 # v43.0.2
        env:
          RENOVATE_HOST_RULES: '[{"hostType": "docker", "matchHost": "ghcr.io", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '[".*"]'
          BUILDER_IMAGE: 'ghcr.io/sovereigncloudstack/cso'
          RENOVATE_POST_UPGRADE_TASKS: '{ commands: ["BUILD_IMAGE_TOKEN=${{ secrets.GITHUB_TOKEN }} BUILD_IMAGE_USER=${{ github.actor }} CI=true ./hack/upgrade-builder-image.sh"], fileFilters: ["Makefile", ".builder-image-version.txt", ".github/**/*.yml", ".github/**/*.yaml"], executionMode: "branch"}'
        with:
          configurationFile: ${{ env.RENOVATE_CONFIG_FILE }}
          token: "x-access-token:${{ steps.generate-token.outputs.token }}"
          mount-docker-socket: "true"
